create table audit_events (
    id bigint generated by default as identity primary key,
    sequence_number bigint not null,
    event_type varchar(100) not null,
    actor_id varchar(100) not null,
    resource_type varchar(100) not null,
    resource_id varchar(150) not null,
    payload text not null,
    occurred_at timestamp with time zone,
    recorded_at timestamp with time zone not null,
    previous_hash varchar(64) not null,
    content_hash varchar(64) not null,
    hash_version integer not null,
    constraint uk_audit_event_sequence unique (sequence_number)
);

create index idx_audit_event_actor on audit_events (actor_id);
create index idx_audit_event_resource on audit_events (resource_type, resource_id);
create index idx_audit_event_type on audit_events (event_type);
create index idx_audit_event_recorded_at on audit_events (recorded_at);

create table chain_state (
    chain_name varchar(50) primary key,
    last_sequence bigint not null,
    last_hash varchar(64) not null
);

insert into chain_state (chain_name, last_sequence, last_hash)
values ('GLOBAL', 0, '0000000000000000000000000000000000000000000000000000000000000000');
