alter table audit_events add column archived boolean not null default false;
alter table audit_events add column archived_at timestamp with time zone;
create index idx_audit_event_archived_recorded on audit_events (archived, recorded_at);

create table redaction_receipts (
    id bigint generated by default as identity primary key,
    target_sequence bigint not null,
    original_content_hash varchar(64) not null,
    json_pointer varchar(500) not null,
    salted_value_hash varchar(64) not null,
    redacted_payload_hash varchar(64) not null,
    requested_by varchar(100) not null,
    reason varchar(500) not null,
    redacted_at timestamp with time zone not null,
    receipt_hash varchar(64) not null,
    constraint uk_redaction_receipt_hash unique (receipt_hash)
);

create index idx_redaction_target on redaction_receipts (target_sequence, redacted_at);
